version: "2"
services:

  # node_exporter
  node_exporter:
    build: exporter

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otelcol/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - node_exporter
      - cortex
    links:
      - "node_exporter"
      - "cortex"
    
  # cortex
  cortex: 
    image: ubuntu/cortex:1.10-21.10_beta
    command: ["-config.file=/single-process-config-blocks.yaml"]
    volumes:
      - ./cortex/single-process-config-blocks.yaml:/single-process-config-blocks.yaml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - cortex
    links:
      - "cortex"