receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: ["node_exporter:9100"]

exporters:
  prometheusremotewrite:
    endpoint: "http://cortex:9009/api/v1/push"
  logging:
    loglevel: info

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [logging,prometheusremotewrite]
